<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsPublishable>true</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hexalith.Timesheets.Projections\Hexalith.Timesheets.Projections.csproj" />
    <ProjectReference Include="..\Hexalith.Timesheets.Server\Hexalith.Timesheets.Server.csproj" />
    <ProjectReference Include="..\Hexalith.Timesheets.ServiceDefaults\Hexalith.Timesheets.ServiceDefaults.csproj" />
    <ProjectReference Include="$(HexalithEventStoreRoot)\src\Hexalith.EventStore.DomainService\Hexalith.EventStore.DomainService.csproj" AdditionalProperties="NuGetAudit=false" />
  </ItemGroup>

</Project>
